# Generated by Django 4.2.11 on 2024-04-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Question",
        ),
    ]
