# Generated by Django 4.2.11 on 2024-04-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("test", "0002_delete_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeoulMunicipalArtMuseum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DP_EX_NO", models.CharField(max_length=10)),
                ("DP_SEQ", models.CharField(max_length=10)),
                ("DP_NAME", models.CharField(max_length=255)),
                ("DP_SUBNAME", models.CharField(blank=True, max_length=255)),
                ("DP_PLACE", models.CharField(max_length=255)),
                ("DP_START", models.DateField()),
                ("DP_END", models.DateField()),
                ("DP_HOMEPAGE", models.URLField(blank=True)),
                ("DP_EVENT", models.CharField(blank=True, max_length=255)),
                ("DP_SPONSOR", models.CharField(max_length=255)),
                ("DP_VIEWTIME", models.CharField(blank=True, max_length=255)),
                ("DP_VIEWCHARGE", models.CharField(blank=True, max_length=255)),
                ("DP_ART_PART", models.TextField()),
                ("DP_ART_CNT", models.CharField(max_length=20)),
                ("DP_ARTIST", models.CharField(max_length=255)),
                ("DP_VIEWPOINT", models.TextField(blank=True)),
                ("DP_INFO", models.TextField()),
                ("DP_MAIN_IMG", models.URLField()),
                ("DP_LNK", models.URLField()),
                ("DP_DATE", models.DateField()),
            ],
        ),
    ]
