# Generated by Django 4.2.11 on 2024-04-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test", "0004_alter_seoulmunicipalartmuseum_dp_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seoulmunicipalartmuseum",
            name="DP_VIEWTIME",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
