# Generated by Django 4.2.11 on 2024-04-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test", "0005_alter_seoulmunicipalartmuseum_dp_viewtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seoulmunicipalartmuseum",
            name="DP_ART_CNT",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="seoulmunicipalartmuseum",
            name="DP_EVENT",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="seoulmunicipalartmuseum",
            name="DP_EX_NO",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="seoulmunicipalartmuseum",
            name="DP_NAME",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="seoulmunicipalartmuseum",
            name="DP_PLACE",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="seoulmunicipalartmuseum",
            name="DP_SEQ",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="seoulmunicipalartmuseum",
            name="DP_SPONSOR",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="seoulmunicipalartmuseum",
            name="DP_SUBNAME",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="seoulmunicipalartmuseum",
            name="DP_VIEWCHARGE",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
