# Generated by Django 4.2.11 on 2024-04-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0007_seoulisartmuseum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seoulisartmuseum",
            name="GA_INS_DATE",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="seoulisartmuseum",
            name="GA_KNAME",
            field=models.CharField(max_length=300),
        ),
    ]
