# Generated by Django 4.2.11 on 2024-04-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0008_alter_seoulisartmuseum_ga_ins_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("REF_ID", models.CharField(max_length=300)),
                ("ADDR", models.CharField(max_length=500)),
                ("NAME", models.CharField(max_length=500)),
                ("X_COORD", models.FloatField(default=0.0)),
                ("Y_COORD", models.FloatField(default=0.0)),
                ("TYPE", models.CharField(max_length=300)),
                ("startDate", models.DateField(blank=True)),
                ("endDate", models.DateField(blank=True)),
            ],
        ),
    ]
