# Generated by Django 4.2.11 on 2024-04-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0009_landmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landmark",
            name="endDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="landmark",
            name="startDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
