# Generated by Django 4.2.11 on 2024-04-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0010_alter_landmark_enddate_alter_landmark_startdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landmark",
            name="endDate",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="landmark",
            name="startDate",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
