# Generated by Django 4.2.11 on 2024-04-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0011_alter_landmark_enddate_alter_landmark_startdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landmark",
            name="X_COORD",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="landmark",
            name="Y_COORD",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
