# Generated by Django 4.2.11 on 2024-04-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0012_alter_landmark_x_coord_alter_landmark_y_coord"),
    ]

    operations = [
        migrations.AddField(
            model_name="landmark",
            name="IMG",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="landmark",
            name="SUBJECT",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="landmark",
            name="TITLE",
            field=models.CharField(default="", max_length=300),
        ),
    ]
