# Generated by Django 4.2.11 on 2024-04-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0013_landmark_img_landmark_subject_landmark_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="CultureEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CODENAME", models.CharField(max_length=300)),
                ("GUNAME", models.CharField(max_length=300)),
                ("TITLE", models.CharField(max_length=300)),
                ("DATE", models.CharField(max_length=300)),
                ("PLACE", models.CharField(max_length=300)),
                ("ORG_NAME", models.CharField(max_length=300)),
                ("USE_TRGT", models.CharField(max_length=300)),
                ("USE_FEE", models.CharField(max_length=300)),
                ("PLAYER", models.CharField(max_length=300)),
                ("PROGRAM", models.CharField(max_length=300)),
                ("ETC_DESC", models.CharField(max_length=300)),
                ("ORG_LINK", models.URLField(default="")),
                ("MAIN_IMG", models.URLField(default="")),
                ("RGSTDATE", models.CharField(max_length=300)),
                ("TICKET", models.CharField(max_length=300)),
                ("STRTDATE", models.CharField(max_length=300)),
                ("END_DATE", models.CharField(max_length=300)),
                ("THEMECODE", models.CharField(max_length=300)),
                ("LOT", models.FloatField(default=0.0)),
                ("LAT", models.FloatField(default=0.0)),
                ("IS_FREE", models.CharField(max_length=300)),
                ("HMPG_ADDR", models.URLField(default="")),
            ],
        ),
    ]
