# Generated by Django 4.2.11 on 2024-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0014_cultureevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="cultureevent",
            name="REF_ID",
            field=models.CharField(default="", max_length=300),
        ),
    ]
