# Generated by Django 4.2.11 on 2024-04-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0015_cultureevent_ref_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cultureevent",
            name="ORG_LINK",
            field=models.CharField(default="", max_length=500),
        ),
    ]
