# Generated by Django 4.2.11 on 2024-04-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0016_alter_cultureevent_org_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cultureevent",
            name="PROGRAM",
            field=models.TextField(),
        ),
    ]
