# Generated by Django 4.2.11 on 2024-04-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0018_alter_cultureevent_use_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cultureevent",
            name="ETC_DESC",
            field=models.TextField(),
        ),
    ]
