# Generated by Django 4.2.11 on 2024-04-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0019_alter_cultureevent_etc_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cultureevent",
            name="LAT",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="cultureevent",
            name="LOT",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
