# Generated by Django 4.2.11 on 2024-04-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0020_alter_cultureevent_lat_alter_cultureevent_lot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cultureevent",
            name="PLAYER",
            field=models.TextField(),
        ),
    ]
