# Generated by Django 4.2.11 on 2024-04-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0013_landmarkfavorite"),
        ("test", "0022_alter_cultureevent_org_link"),
    ]

    operations = []
