# Generated by Django 4.2.11 on 2024-05-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0025_alter_searchhistory_landmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="landmark",
            name="URL",
            field=models.URLField(default=""),
        ),
    ]
